version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      ['start', '8000']
    networks:
      - default

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_PASSWORD=app_pswd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
      default:
          driver: bridge